version: '3'
services:
  webapp:
    ports: 
      - "8090:8090"
      - "4090:4090"
    env_file:
      - ./server/.env
    environment:
      - VOLUME=/var/storage
    volumes:
      - storage:/var/storage
    build: .